### PR TITLE
Scaffold for package example usages

### PR DESCRIPTION
**Pull request by rockacola**
Add some example usages in ES6 syntax.

### CODE REVIEW

**Comment by lllwvlvwlll** [comment]
Looks good.  What is the use of the Nodes attribute in the 'profiles' file?  

Also consider calling neo.nodeWithBlock(blockIndex, 'latency', false) on the block related requests to get the fastest node that has been verified to have a certain block.  This will prevent the request hitting a node that does not have the block once we get dynamic seed registration up and running.  Eventually, we'll abstract all the RPC/local db calls and toggle based on optional parameters and the mode.

Other than that this is awesome!

**Comment by notatestuser** [comment]
Would be good to use async/await in these as there's so much promise action

**Comment by rockacola** [comment]
> What is the use of the Nodes attribute in the 'profiles' file?

You are right, the "nodes" are not provide any use, thus is now removed.

**Comment by rockacola** [comment]
>consider calling neo.nodeWithBlock(blockIndex, 'latency', false) on the block related requests to get the fastest node that has been verified to have a certain block.

@lllwvlvwlll, Can you provide code example?
My understanding is that you will need an active node in order to obtain current block height (which I assume is the value required for `blockIndex`?), which means you must have an local instance running for `neo.nodeWithBlock(blockIndex, 'latency', false)` to work, correct?

**Comment by rockacola** [comment]
> Would be good to use async/await in these as there's so much promise action

@notatestuser, async/await are already in-use in `node-app.js`. Or can you recommend further optimisation?

On a side note, I'm actually thinking of dumbing it down to Promise chain or even callback loops. Reason is, these examples are meant to be additional guidance for new developers of all level, and not everyone is comfortable (or has the environment setup) for ES2017 syntax.

**Comment by notatestuser** [comment]
Applying async/await in a few places could improve the readability a lot:

Before:
```js
const getBlockCountDemo = function () {
  console.log('getBlockCountDemo:');
  return new Promise((resolve) => {
    neoNode.getBlockCount()
      .then(function (res) {
        console.log(res);
        // console.log(res.data.result);
        resolve();
      })
      .catch(function (err) {
        console.log('error:');
        console.log(err);
        resolve();
      });
  });
};
```

After:
```js
async function getBlockCountDemo() {
  try {
    const blockCount = await neoNode.getBlockCount();
  } catch (err) {
    console.log('error:', err);
  }
  return blockCount;
}
```

Returns a promise as before.

**Comment by rockacola** [comment]
@notatestuser, thanks for recommendations. examples updated accordingly.

**Comment by lllwvlvwlll** [comment]
neoNode = neoBlockchain.fastestNode();

But the response this method will provide will change over time depending on which node is fastest.  There is also the risk of being connected to a node which does not have the block you request because it isn't fully synced.

neoBlockchain.nodeWithBlock(10000, 'latency', true).getBlock(10000)

In the near future, all the methods will be abstracted and the core controller will automatically route to the best node (local or remote) depending on what the request was: neoBlockchain.getBlock(10000)

**Comment by rockacola** [comment]
@lllwvlvwlll, after further evaluations, I've managed to obtain a valid node with:
`neoBlockchain.nodeWithBlock(-1, 'latency', false)`

That is because all nodes in `blockchain.nodes` have `blockHeight; 0` and `index: -1`. For example:

```
{
    domain: 'http://test1.cityofzion.io',
    port: 8880,
    age: 0,
    active: true,
    latency: 0,
    blockHeight: 0,
    index: -1,
    connections: 0,
    pendingRequests: 1,
    getBalance: [Function],
    getBestBlockHash: [Function],
    getBlock: [Function],
    getBlockCount: [Function],
    getBlockHash: [Function],
    getConnectionCount: [Function],
    getRawMemPool: [Function],
    getRawTransaction: [Function],
    getTXOut: [Function],
    sendRawTransaction: [Function],
    sendToAddress: [Function],
    submitBlock: [Function],
    call: [Function],
    deferredUpdateLoop: [Function]
}
```

Is that the expected behaviour?

Bit of background on my setup:
* I'm developing on macOS, NodeJS 8.4
* No localhost mongo instance

**Comment by lllwvlvwlll** [comment]
@rockacola How are you running the code? 
When you initialize a blockchain instance, it needs to get in contact with the nodes before they become 'available' for querying using that method.  If you are instantiating, then immediately calling that method, the nodes may not have become active yet.

try it with a 5 second setTimeout.  You can also try explicitly picking a node and making the call directly:
neoBlockchain.nodes[0]

**Comment by rockacola** [comment]
@lllwvlvwlll, for testing/demonstration purpose, I can explicitly picking up a node directly with `neoBlockchain.nodes[0]`.

Also, I'm restructure examples to make it a self documentation (oppose to just run through list of endpoints undocumented).

It may make sense to close/reject this PR until I'm ready with updates.

**Pull request closed without merging**
